# Generated by Django 2.2.12 on 2022-01-19 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='dependentes',
            field=models.ManyToManyField(blank=True, to='clientes.Dependente'),
        ),
    ]
