# Generated by Django 2.2.12 on 2022-01-19 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20220119_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Dependente',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dependentes',
            field=models.ManyToManyField(blank=True, to='clientes.Dependento'),
        ),
    ]
