# Generated by Django 2.2.12 on 2022-01-19 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20220119_0146'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dependento',
            new_name='Dependente',
        ),
    ]
