# Generated by Django 2.2.12 on 2022-01-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20220119_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
