# Generated by Django 2.2.12 on 2022-01-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cliente_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(upload_to='clientes_fotos'),
        ),
    ]
